=== MuNuChapterHKN/HKrecruitment/hkrecruitment-apiserver/src/config/json-schema/messageTemplate.json
{
    "$schema":"http://json-schema.org/draft-06/schema#",
    "id": "https://hknpolito.org/schemas/v1/messageTemplate.json#",
    "title": "messageTemplates",
    "type":"object",
    "definitions": {
        "messageKey": {
            "enum": ["name", "surname", "additionalText", "start", "end"]
        },
        "vocabularyEntry": {
            "type": "object",
            "properties": {
                "placeholder": {"type": "string"},
                "male": {"type": "string"},
                "female": {"type": "string"}
            },
            "additionalProperties": false,
            "required": ["placeholder", "male", "female"]
        },
        "messageVocabulary": {
            "type": "array",
            "items": {"$ref": "#/definitions/vocabularyEntry"},
            "uniqueItems": true
        },
        "message":{
            "type":"object",
            "properties": {
                "subject": {"type": "string"},
                "body":{"type":"string"},
                "fields": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/messageKey"},
                    "uniqueItems": true
                },
                "vocabulary": {"$ref": "#/definitions/messageVocabulary"}
            },
            "additionalProperties": false,
            "required": ["subject","body", "fields", "vocabulary"]
        },
        "messageTemplate": {
            "type": "object",
            "properties": {
                "ita": {"$ref": "#/definitions/message"},
                "eng": {"$ref": "#/definitions/message"}
            },
            "required": ["ita", "eng"],
            "additionalProperties": false
        }
    },
    "properties": {
        "new_application":{ "$ref": "#/definitions/messageTemplate"},
        "application_accepted":{ "$ref": "#/definitions/messageTemplate"},
        "application_revocated":{ "$ref": "#/definitions/messageTemplate"},
        "require_availability_confirmation":{ "$ref": "#/definitions/messageTemplate"},
        "slot_reserved":{ "$ref": "#/definitions/messageTemplate"},
        "interview_member_accepted":{ "$ref": "#/definitions/messageTemplate"},
        "interview_mentee_accepted":{ "$ref": "#/definitions/messageTemplate"},
        "interview_rejected":{ "$ref": "#/definitions/messageTemplate"}
    },
    "additionalProperties": false,
    "required": ["new_application", "application_accepted", "application_revocated",
        "require_availability_confirmation", "slot_reserved", "interview_member_accepted",
        "interview_mentee_accepted", "interview_rejected"]
}

=== MuNuChapterHKN/HKrecruitment/hkrecruitment-apiserver/test/validationData/mailTemplates.json
{
  "$schema": "../../src/config/json-schema/messageTemplate.json",
  "new_application": {
    "ita": {
      "subject": "[name surname] Candidatura accettata!",
      "body": "Car name surname, la tua candidatura è stata accettata!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "application_accepted": {
    "ita": {
      "subject": "[name surname] Candidatura accettata!",
      "body": "Car name surname, la tua candidatura è stata accettata!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "application_revocated": {
    "ita": {
      "subject": "[name surname] Candidatura revocata!",
      "body": "Car name surname, ci dispiace sapere che hai deciso di cancellare la tua candidatura",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "require_availability_confirmation": {
    "ita": {
      "subject": "[name surname] Conferma la tua disponibilità!",
      "body": "Gentile HKnuer name surname, conferma la tua disponibilità per start-end!",
      "fields": [
        "name",
        "surname",
        "start",
        "end"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "slot_reserved": {
    "ita": {
      "subject": "[name surname] Colloquio pianificato!",
      "body": "Car name surname, il tuo colloquio è stato fissato per start, trovi i dettagli sulla tua pagina e sull'evento Google Calendar!",
      "fields": [
        "name",
        "surname",
        "start"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "interview_member_accepted": {
    "ita": {
      "subject": "[name surname] Benvenuto in HKN!",
      "body": "Car name surname, a seguito del nostro colloquio tenutosi start, abbiamo deciso che saremmo felici se tu ti unissi ad HKN!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "interview_mentee_accepted": {
    "ita": {
      "subject": "[name surname] Candidatura accettata!",
      "body": "Car name surname, la tua candidatura è stata accettata!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  },
  "interview_rejected": {
    "ita": {
      "subject": "[name surname] Candidatura accettata!",
      "body": "Car name surname, la tua candidatura è stata accettata!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": [
        {
          "placeholder": "Car",
          "female": "Cara",
          "male": "Caro"
        }
      ]
    },
    "eng": {
      "subject": "[name surname] Application accepted!",
      "body": "Dear name surname, your application has been accepted!",
      "fields": [
        "name",
        "surname"
      ],
      "vocabulary": []
    }
  }
}
